baseURL: https://blog.amosino.net
languageCode: en
DefaultContentLanguage: en
title: Econometría & Co.
theme: anatole
summarylength: 10
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
localizedDates: no
markup:
  goldmark:
    renderer:
      unsafe: yes
taxonomies:
  category: categories
  series: series
  tag: tags
related:
  includeNewer: yes
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 80
  threshold: 80
  toLower: yes
