[es]
title = "My blog"
weight = 1
LanguageName = "ES"
contentDir = "content/espanol"


[en]
title = "My blog"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

#[ar]
#title = "فلانة الفلانية"
#description = "أنا أعمل كمطورة ويب في شركة س"
#contentDir = "content/arabic" 
#weight = 2
#LanguageDirection = "rtl" 
#LanguageName = "AR"
