  [[main]]
  name = "Home"
  identifier = "principal"
  weight = 100
  url = "/es/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/es/post/"

  #[[main]]
  #name = "Portfolio"
  #weight = 300
  #identifier = "portfolio"
  #url = "/portfolio/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/es/about/"

  #[[main]]
  #name = "Accomplishments"
  #weight = 500
  #identifier = "accomplishments"

  #[[main]]
  #name = "Awards"
  #weight = 510
  #identifier = "awards"
  #url = "/awards/"
  #parent = "accomplishments"  

  #[[main]]
  #name = "Certifications"
  #weight = 520
  #identifier = "certifications"
  #url = "/certifications/"
  #parent = "accomplishments"

  #[[main]]
  #name = "Contact"
  #weight = 600
  #identifier = "contact"
  #url = "/contact/"

  #[[footer]]
  #name = "imprint"
  #weight = 1
  #identifier = "imprint"
  #url = "/imprint/"